### ISSUE TITLE
Panic while using glow directly

### ISSUE THREAD

**Issue by xlab** [go-gl/glfw#171]
Hi, I took the example app from README of this project, initialised the glfw and made the context current. The app works fine (shows a window).

```
    err := glfw.Init()
    if err != nil {
        panic(err)
    }
    defer glfw.Terminate()

    window, err := glfw.CreateWindow(640, 480, "Testing", nil, nil)
    if err != nil {
        panic(err)
    }

    window.MakeContextCurrent()
```

But then after `window.MakeContextCurrent` I added 

```
gl.Viewport(0, 0, 640, 480)
```

And it panics:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x40cf016, 0x2a)
    /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc
runtime.asmcgocall(0xc42004fe30, 0xc420014100)
    /usr/local/go/src/runtime/asm_amd64.s:594 +0x70
runtime.cgocall(0x7fff5fbff240, 0x4135920, 0x7fff5fbff230)
    /usr/local/go/src/runtime/cgocall.go:115 +0xed

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4098e00, 0xc42004feb0, 0xc400000000)
    /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc42004fe60 sp=0xc42004fe20
github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowViewport(0x0, 0x0, 0x25800000320)
    github.com/go-gl/gl/v3.3-core/gl/_obj/_cgo_gotypes.go:17161 +0x45 fp=0xc42004feb0 sp=0xc42004fe60
github.com/go-gl/gl/v3.3-core/gl.Viewport(0x0, 0x25800000320)
    /Users/xlab/Documents/dev/go/src/github.com/go-gl/gl/v3.3-core/gl/package.go:10052 +0x4d fp=0xc42004fed8 sp=0xc42004feb0
main.main()
```

I have OS X and Go 1.7

**Comment by tapir** [comment]
Did you do

``` Go
    // Important! Call gl.Init only under the presence of an active OpenGL context,
    // i.e., after MakeContextCurrent.
    if err := gl.Init(); err != nil {
        panic(err)
    }
```

**Comment by xlab** [comment]
In this example they call it before glew Init: https://github.com/vurtun/nuklear/blob/master/demo/glfw_opengl3/main.c#L81-L85

``` c
    win = glfwCreateWindow(WINDOW_WIDTH, WINDOW_HEIGHT, "Demo", NULL, NULL);
    glfwMakeContextCurrent(win);
    glfwGetWindowSize(win, &width, &height);

    /* OpenGL */
    glViewport(0, 0, WINDOW_WIDTH, WINDOW_HEIGHT);
    glewExperimental = 1;
    if (glewInit() != GLEW_OK) {
        fprintf(stderr, "Failed to setup GLEW\n");
        exit(1);
    }
```

**Comment by tapir** [comment]
not the same thing

**Comment by xlab** [comment]
This is madness. I even made my own bindings for GLFW and got the same results.

It turns out, I've accidentally included `-lGLEW` in LDFLAGS of the package I'm currently working on, so this CONFLICTS WITH **GLOW**~!! And despite having `gl.Init()` in place, `glCreateProgram()` call would cause an access violation crash, as if I didn't do `gl.Init()`, seems like glew corrupts the state. Removed `-lGLEW` and now it works.

x(
