### ISSUE TITLE
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: Win32: Failed to convert clipboard to string: 操作成功完成。 GLFW: Please report this bug in the Go package immediately.

### ISSUE THREAD

**Issue by leielyq** [go-gl/glfw#301]
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: Win32: Failed to convert clipboard to string: 操作成功完成。
GLFW: Please report this bug in the Go package immediately.

**Comment by pwaller** [comment]
Please include steps to reproduce and ideally a reproducer program. The error message indicates this may be a go-gl/glfw bug, which we would like to fix if we can reproduce it.

**Comment by kechkibet** [comment]
Hi,
We are also experiencing this issue when client types on keyboard on go-flutter desktop.

**Comment by pchampio** [comment]
The go-flutter related issue: https://github.com/go-flutter-desktop/go-flutter/issues/537
Maybe what's happening is a GLFW_NOT_INITIALIZED error is thrown, then a FormatUnavailable error is thrown concurrently?

Some logs:
```
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: Win32: Failed to convert clipboard to string: 操作成功完成。
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: Win32: Failed to convert clipboard to string: 操作成功完成。

goroutine 17 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0xc0000050c0, 0x0)
        C:/Users/yangyakun/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:178 +0x208
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        C:/Users/yangyakun/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:185
github.com/go-gl/glfw/v3.3/glfw.PostEmptyEvent()
        C:/Users/yangyakun/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:1007 +0x3f
github.com/go-flutter-desktop/go-flutter.(*EventLoop).PostTask(0xc0000a7470, 0xe308570, 0x7ff9a213c900, 0x21255b1fd1a4)
        C:/Users/yangyakun/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/event-loop.go:73 +0x139
github.com/go-flutter-desktop/go-flutter/embedder.proxy_post_task_callback(...)
        C:/Users/yangyakun/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/embedder/embedder_proxy.go:94
github.com/go-flutter-desktop/go-flutter/embedder._cgoexpwrap_1d54f1096e3c_proxy_post_task_callback(0xe308570, 0x7ff9a213c900, 0x21255b1fd1a4, 0xc00000a528)
        _cgo_gotypes.go:906 +0x53
hover: App 'saas_clinicsys' exited with error: exit status 2
```
And another one:
```
goroutine 6146 [running]:
runtime/debug.Stack(0x0, 0x1b01ca0, 0xc000088a50)
	c:/go/src/runtime/debug/stack.go:24 +0xa5
runtime/debug.PrintStack()
	c:/go/src/runtime/debug/stack.go:16 +0x29
github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleMethodCall.func1(0xc00001c240, 0x13, 0xc00028c420)
	C:/Users/ee/Workspace/go-flutter/plugin/method-channel.go:219 +0x15f
panic(0x1966300, 0xc0000b6160)
	c:/go/src/runtime/panic.go:969 +0x1c7
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0xc000253d60, 0x123f5ab)
	C:/Users/ee/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:178 +0x20c
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	C:/Users/ee/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:185
github.com/go-gl/glfw/v3.3/glfw.PostEmptyEvent()
	C:/Users/ee/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:1007 +0x3f
github.com/go-flutter-desktop/go-flutter.responseSender.Send(0xc0001cebe0, 0xc000088750, 0xc0000061c8, 0xc000098140, 0x6, 0x40)
	C:/Users/ee/Workspace/go-flutter/messenger.go:129 +0x5a
github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleMethodCall(0xc00028c420, 0x1b02300, 0xc000283650, 0xc00001c240, 0x13, 0x0, 0x0, 0x1b02280, 0xc0001f2040)
	C:/Users/ee/Workspace/go-flutter/plugin/method-channel.go:246 +0x518
created by github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleChannelMessage
	C:/Users/ee/Workspace/go-flutter/plugin/method-channel.go:207 +0x271
panic: FormatUnavailable: Win32: Failed to convert clipboard to string: 操作成功完成。 

goroutine 18 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0xc000005f60, 0x1)
	C:/Users/ee/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:178 +0x20c
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	C:/Users/ee/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:185
github.com/go-gl/glfw/v3.3/glfw.PostEmptyEvent()
	C:/Users/ee/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:1007 +0x3f
github.com/go-flutter-desktop/go-flutter.(*EventLoop).PostTask(0xc0001c1e90, 0x2f47c130, 0x2dc51b38, 0x15324a2d6b2c)
	C:/Users/ee/Workspace/go-flutter/event-loop.go:73 +0x12e
github.com/go-flutter-desktop/go-flutter/embedder.proxy_post_task_callback(...)
	C:/Users/ee/Workspace/go-flutter/embedder/embedder_proxy.go:94
github.com/go-flutter-desktop/go-flutter/embedder._cgoexpwrap_de84f3eb1d92_proxy_post_task_callback(0x2f47c130, 0x2dc51b38, 0x15324a2d6b2c, 0xc0001e80d8)
	_cgo_gotypes.go:916 +0x52
```

**Comment by pchampio** [comment]
@kechkibet can you share the full logs ?
It happens when the app start up ? or when the client starts typing ? Are you running on windows ?

**Comment by kechkibet** [comment]
Hi,
The issue happens unpredictably;

https://youtu.be/SEjEx_KMalk

**Comment by pchampio** [comment]
@kechkibet I've wrapped `glfw.PostEmptyEvent` with defer-recover which seems to be the function that causes panic.
can you check the https://github.com/go-flutter-desktop/go-flutter/issues/537#issuecomment-799319422

**Comment by kechkibet** [comment]
Let me try; can i build release with these options?

**Comment by pchampio** [comment]
Yes (please use the go-flutter tracker for go-flutter related questions^^)

**Comment by kechkibet** [comment]
Sorry and thanks. Will revert once done.
