### ISSUE TITLE
panic when using fyne and ebiten simultaneously

### ISSUE THREAD

**Issue by ghost** [go-gl/glfw#320]
I'm trying to use ebiten make a game, and I decided to use fyne as main UI,
but when I use these 2 at the same time, it panicked.

error message:
```
GLFW: An invalid error was not accepted by the caller: ErrorCode(65546): Cannot make current with a window that has no OpenGL or OpenGL ES context
GLFW: Please report this bug in the Go package immediately.
panic: ErrorCode(65546): Cannot make current with a window that has no OpenGL or OpenGL ES context

goroutine 14 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/lemtea/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/error.go:178 +0x20c
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /home/lemtea/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/error.go:185
github.com/go-gl/glfw/v3.3/glfw.(*Window).MakeContextCurrent(0xc000142480)
        /home/lemtea/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/context.go:18 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0005c01c0, 0xc0000204b0)
        /home/lemtea/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1202 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc00059c140, 0xc000032600, 0xc00059c230)
        /home/lemtea/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:189 +0x13a
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
        /home/lemtea/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:181 +0xbd
exit status 2
```

It says that I shout report to the community, so I'm here.
How to solve this problem? or it is a bug?
thanks.

platform:
KDE neon 5.21
Kernel Version: 5.4.0-73-generic
Graphics Platform: X11

go 1.16.3
ebiten v2.1.1
fyne v2.0.3

**Comment by tapir** [comment]
Hello,

can you provide a sample code?

**Comment by ghost** [comment]
for example:
```
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
	"github.com/hajimehoshi/ebiten/v2"
)

type game struct {
}

func (g *game) Update() error {
	return nil
}

func (g *game) Draw(screen *ebiten.Image) {
}

func (g *game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return outsideWidth, outsideHeight
}

func runEbiten() {
	ebiten.SetWindowSize(600, 600)
	ebiten.SetWindowTitle("test")

	g := &game{}
	if err := ebiten.RunGame(g); err != nil {
		panic(err)
	}
}

func main() {
	w := app.New().NewWindow("test")

	w.Resize(fyne.NewSize(800.0, 600.0))
	w.ShowAndRun()

	b := widget.NewButton("test", runEbiten)
	w.SetContent(b)
}
```

I was trying to use a button to launch ebiten,
but this panicked.

**Comment by hajimehoshi** [comment]
I don't think multiple GLFW applications (Fyne and Ebiten) work in one process.

**Comment by tapir** [comment]
Both Ebiten and Fyne handles the window/context creation themselves (via GLFW) so I guess this is no surprise. You could make them share the context but that would require modification to both libraries.

**Comment by ghost** [comment]
Thanks everyone for helping
